// build.js — concatenates the scripts/ sources into public/atella.js,
// the single file served by the CDN and loaded site-wide in Webflow.
//
// Run:  node build.js
//
// Each source in scripts/ is a standalone IIFE that detects its own page
// and only runs there, so bundling them is safe. shared-cache.js must come
// first because it defines window.MSDataCache, which the others depend on.
'use strict';

var fs = require('fs');
var path = require('path');

// Load order. shared-cache.js first; page scripts after (order among them
// doesn't matter — each guards on its own page marker).
var ORDER = [
  'shared-cache.js',
  'dashboard.js',
  'course-detail.js',
  'lesson-detail.js',
  'module-detail.js',
  'all-courses.js',
  'member-all-courses.js',
  'enrolled-courses.js',
  'saved-courses.js',
  'nav-courses.js'
];

// Strip the Webflow embed wrapper: <script>/</script> tags and single-line
// <!-- … --> HTML comments. What's left is plain JavaScript.
function strip(src) {
  return src.split('\n').filter(function (line) {
    var t = line.trim();
    if (t === '<script>' || t === '</script>') return false;
    if (t.indexOf('<!--') === 0 && t.slice(-3) === '-->') return false;
    return true;
  }).join('\n').trim();
}

var out = [
  '/* Atella — combined site script.',
  ' * GENERATED by build.js from scripts/. Do NOT edit this file directly —',
  ' * edit the sources in scripts/ and re-run `node build.js`.',
  ' */',
  ''
];

ORDER.forEach(function (name) {
  var src = fs.readFileSync(path.join(__dirname, 'scripts', name), 'utf8');
  out.push('/* ===================== ' + name + ' ===================== */');
  out.push(strip(src));
  out.push('');
});

var publicDir = path.join(__dirname, 'public');
if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir);
fs.writeFileSync(path.join(publicDir, 'atella.js'), out.join('\n'));
console.log('Built public/atella.js from ' + ORDER.length + ' source files.');
